[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]
ffi = true
allow_paths = ["../../node_modules"]
remappings = [
    "@openzeppelin/=../../node_modules/@openzeppelin/",
    "@uniswap/=../../node_modules/@uniswap/"
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
