name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        # Use pnpm version from package.json "packageManager" to avoid version mismatch
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Foundry (stable)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Forge tests
        run: |
          cd packages/contracts
          forge test -vvv


